# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "abra-assessment"
client_id = "56375a8cfe4c5c1138d5f56f02cad774"
application_url = "https://similarly-tech-citizen-recorded.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts"

[auth]
redirect_urls = [
  "https://similarly-tech-citizen-recorded.trycloudflare.com/auth/callback",
  "https://similarly-tech-citizen-recorded.trycloudflare.com/auth/shopify/callback",
  "https://similarly-tech-citizen-recorded.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "hugofusinato.myshopify.com"
